### PR TITLE
feature: added more array access options

### PR DESCRIPTION
**Pull request by mlaggner**
- added index range access for arrays: ${array[m,n]}
  get a new array with a subset of the original array, starting with index m and n entries
- added index range end access for arrays: ${array[m,]}
  get a new array with a subset of the original array, starting with index m until the end of the array
- added string index access: ${string[m]}
  get the m. character of the string
- added string range access: ${string[m,n]}
  get a substring starting with the offset m and n characters length
- added string range end acess: ${string[m,]}
  get a substring starting with the offset m until the end of the string

m ... index/offset
n ... count/length

### CODE REVIEW

**Comment by DJCordhose** [comment]
Great addition, thanks a lot for contributing!

**Comment by mlaggner** [comment]
thanks.
Are there any plans for releasing v4.0.0 to maven?

**Comment by DJCordhose** [comment]
Hey, would be the the perfect time now. Not sure why, but I always have a hard time making releases to maven central. Would you like to do that?

**Comment by DJCordhose** [comment]
Everything is prepared for a release, just need someone to help me with https://github.com/DJCordhose/jmte/issues/6

**Pull request merged**
